### ISSUE TITLE
Hours from an inactive Iteration are contabilized

### ISSUE THREAD

**Issue by eduardoguilarducci** [NielZeeman/team-capacity-extension#2]
When you have an inactive iteration (date of the end of this iteration is in the past), the capacity hours of a team member that was in that iteration still counting on panel. 
We expect that this hours do not be accounted in he capacity panel.

**Comment by NielZeeman** [comment]
Hi @eduardoguilarducci ,
Thank you for your comment. This is simply using the default team iteration as per the system. 
I'll see about changing it to look at actual "active" iterations, i.e what VSTS deems as active, but has an open or later end-date.

**Comment by eduardoguilarducci** [comment]
Hello, @NielZeeman,
Thanks for your reply.
I just tried to set the default team iteration to @CurrentIteration and did not solve. 
I tried to set other iterations too, but even so, the hours still counting.
If you could change this, that will be very helpfull to manage and plan the team capacity over the time.

**Comment by NielZeeman** [comment]
Hi @eduardoguilarducci 

Not sure I follow, but I think I have the idea.
In VSTS, iterations with dates supersede these that do not. So it will use the last iteration that has/had dates as apposed to any without as the default iteration. 
As an interim work around, you can change the team's default iteration (instead of @currentiteration) to an iteration that does not have any capacities set (or an iteration without start/end date), and that would then ignore them.

**Comment by eduardoguilarducci** [comment]
Thank you @NielZeeman, 

I added an iteration with no capacity at all, after the "last" iteration, and the hours are not counting on the panel.
For a temp is valid, but I think you should consider this scenario and make some changes to reflect that whitout this workaround.

Thank you again!

**Comment by NielZeeman** [comment]
I have published version v0.0.12 that ignores iterations with the end date in the past, if it is the current one

**Comment by eduardoguilarducci** [comment]
@NielZeeman  thank you man! 

I will test this tomorrow and let you know, 

regards
